# MODULES CONFIG
# lines must be the same as tools/mk/modules_conf_default.mk

CFG_MAIXPY_LVGL_SUPPORT=y
CFG_MAIXPY_NES_SUPPORT=y
CFG_MAIXPY_VIDEO_SUPPORT=y
CFG_MAIXPY_OMV_MINIMUM=n
CFG_MAIXPY_TOUCH_SCREEN_SUPPORT=y
CFG_MAIXPY_TOUCH_SCREEN_DRIVER=ft52xx
CFG_MAIXPY_M5STICK=n
CFG_MAIXPY_TOUCH_SUPPORT=y
CFG_MAIXPY_TTGO=y





